### ISSUE TITLE
abcache failing to download Asset Bundle Index

### ISSUE THREAD

**Issue by protofailure** [mos9527/sssekai#1]
Hey, just trying to use this, and running abcache fails when it attempts to download the asset bundle index.
```
PS C:\Users\skidu\OneDrive\Desktop\JPSEKAI ASSETS> sssekai abcache
Downloading: 0.0%|                                                                             | 0.00/0.00 ?B/s 00:00<?2024-02-16 10:06:22 sssekai.abcache [INFO] Loaded 0 entries from cache index
2024-02-16 10:06:22 sssekai.abcache [INFO] Downloading Asset Bundle Index
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Scripts\sssekai.exe\__main__.py", line 7, in <module>
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\__main__.py", line 70, in __main__
    args.func(args)
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\entrypoint\abcache.py", line 13, in main_abcache
    cache.update_cahce_index()
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\abcache\__init__.py", line 137, in update_cahce_index
    dl = self.download_cache_index()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\abcache\__init__.py", line 118, in download_cache_index
    resp.raise_for_status()
  File "C:\Users\skidu\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://production-cf2d2388-assetbundle-info.sekai.colorfulpalette.org/api/version/3.3.0.20/os/android
Downloading: 0.0%|                                                                             | 0.00/0.00 ?B/s 00:00<?
PS C:\Users\skidu\OneDrive\Desktop\JPSEKAI ASSETS>
```
Maybe the cookies here expired?
https://github.com/mos9527/sssekai/blob/7712dfddfe7152fccb11e9da1e4b1ffc31321b2a/sssekai/abcache/__init__.py#L22
I'm not very knowledgeable on this kind of thing, sorry!

**Comment by mos9527** [comment]
The cookies should cause no problems now as they are now automatically updated on boot, since [Version 0.0.4](https://github.com/mos9527/sssekai/commit/9b7516fc355c4d71cbaa25a3479af98ad12b36ad).

Some other QoL changes are added as well. You can read them in [the commit message](https://github.com/mos9527/sssekai/commit/9b7516fc355c4d71cbaa25a3479af98ad12b36ad)!

BTW, you can always check the help information by invoking `sssekai abcache -h`. For [Version 0.0.5](https://github.com/mos9527/sssekai/commit/cd15d4fa7f9ac696dd2ee6507477493f4bea6068) (latest as of this message), it looks like this:
```
usage: sssekai abcache [-h] [--cache-dir CACHE_DIR] [--skip-update] [--version VERSION] [--platform PLATFORM] [--open]

options:
  -h, --help            show this help message and exit
  --cache-dir CACHE_DIR
                        cache directory (default: ~/.sssekai/abcache)
  --skip-update         skip all updates and use cached assets as is.
  --version VERSION     PJSK app version (default: 3.3.1)
  --platform PLATFORM   PJSK app platform (default: android)
  --open                open cache directory. this will skip all updates.
```
You may want to specifiy `--cache-dir` if you want to store the downloaded assets outside your home folder.

Sorry for the troubles. I hope everything works now!

**Comment by protofailure** [comment]
Can confirm that it works now. Thank you!
