### ISSUE TITLE
I'm having an issue with extract appHash funciton

### ISSUE THREAD

**Issue by minhtrietvn2** [mos9527/sssekai#7]
Hello, I'm not sure if this is an error, but when I try to extract appHash, I encounter the error shown in the below. How can i fix it?

Fetching latest game package from APKPure
Downloading 172508113/172508113
Package Type: STAMP_TYPE_DISTRIBUTION_APK
Version: 4.0.5
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\minht\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\__main__.py", line 255, in <module>
    __main__()
  File "C:\Users\minht\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\__main__.py", line 249, in __main__
    args.func(args)
  File "C:\Users\minht\AppData\Local\Programs\Python\Python312\Lib\site-packages\sssekai\entrypoint\apphash.py", line 96, in main_apphash
    env.load_file(stream)
    ^^^
UnboundLocalError: cannot access local variable 'env' where it is not associated with a value

**Comment by mos9527** [comment]
[0.4.6](https://github.com/mos9527/sssekai/releases/tag/0.4.6) should fix it.

**Comment by minhtrietvn2** [comment]
Thanks you so much!
